import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/page";
import Footer from "./components/Screens/Footer/Footer"
import { ThemeProvider } from "next-themes";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dynato Technical Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class">
        <Navbar />
      {children}
      <Footer/>
      </ThemeProvider>
      </body>
    </html>
  );
}
